"""indexes-UniqueConstraint

Revision ID: 14a360988439
Revises: b0252dcaa5e4
Create Date: 2025-09-06 14:36:32.174260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a360988439'
down_revision = 'b0252dcaa5e4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_mfg_segments_tid_range', 'mfg_segment', ['transcript_id', 'start_ts', 'end_ts'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mfg_segments_tid_range', 'mfg_segment', type_='unique')
    # ### end Alembic commands ###