"""mfg_job, mfg_job_event, mfg_speaker and indexes

Revision ID: b0252dcaa5e4
Revises: aa928d52824e
Create Date: 2025-09-05 17:25:43.738222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0252dcaa5e4'
down_revision = 'aa928d52824e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfg_job',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker_node', sa.String(length=128), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['mfg_transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfg_job_transcript_id'), 'mfg_job', ['transcript_id'], unique=True)
    op.create_table('mfg_job_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['mfg_transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfg_job_event_transcript_id'), 'mfg_job_event', ['transcript_id'], unique=False)
    op.create_table('mfg_speaker',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['mfg_transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfg_speaker_transcript_id'), 'mfg_speaker', ['transcript_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mfg_speaker_transcript_id'), table_name='mfg_speaker')
    op.drop_table('mfg_speaker')
    op.drop_index(op.f('ix_mfg_job_event_transcript_id'), table_name='mfg_job_event')
    op.drop_table('mfg_job_event')
    op.drop_index(op.f('ix_mfg_job_transcript_id'), table_name='mfg_job')
    op.drop_table('mfg_job')
    # ### end Alembic commands ###