"""init

Revision ID: 70c3d238f43c
Revises: 
Create Date: 2025-08-27 13:36:50.478119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '70c3d238f43c'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfg_transcript',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('message_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_text', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('mfg_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mfg_chat',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('href_to', sa.Text(), nullable=True),
    sa.Column('secretaria', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('voice_path', sa.Text(), nullable=True),
    sa.Column('audio_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['mfg_transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mfg_segment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('start_ts', sa.Integer(), nullable=True),
    sa.Column('end_ts', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['mfg_transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mfg_embedding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['mfg_segment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mfg_embedding')
    op.drop_table('mfg_segment')
    op.drop_table('mfg_chat')
    op.drop_table('mfg_transcript')
    # ### end Alembic commands ###