"""auth_refresh_token

Revision ID: 1112c043cdaf
Revises: b8a1afcaf2c1
Create Date: 2025-09-20 17:37:50.337179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1112c043cdaf'
down_revision = 'b8a1afcaf2c1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_refresh_token',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['auth_refresh_token.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['mfg_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_refresh_token_fingerprint'), 'auth_refresh_token', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_auth_refresh_token_user_id'), 'auth_refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_refresh_token_user_id'), table_name='auth_refresh_token')
    op.drop_index(op.f('ix_auth_refresh_token_fingerprint'), table_name='auth_refresh_token')
    op.drop_table('auth_refresh_token')
    # ### end Alembic commands ###