"""add mode to mfg_segment

Revision ID: 307ee2af9a09
Revises: 68be4f574763
Create Date: 2025-10-06 15:38:28.135852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307ee2af9a09'
down_revision = '68be4f574763'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfg_segment', sa.Column('mode', sa.String(), server_default='diarize', nullable=False))
    op.drop_constraint(op.f('uq_mfg_segments_tid_range'), 'mfg_segment', type_='unique')
    op.create_index(op.f('ix_mfg_segment_mode'), 'mfg_segment', ['mode'], unique=False)
    op.create_index('ix_mfg_segment_tid_mode', 'mfg_segment', ['transcript_id', 'mode'], unique=False)
    op.create_unique_constraint('uq_mfg_segment_range_mode', 'mfg_segment', ['transcript_id', 'start_ts', 'end_ts', 'mode'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mfg_segment_range_mode', 'mfg_segment', type_='unique')
    op.drop_index('ix_mfg_segment_tid_mode', table_name='mfg_segment')
    op.drop_index(op.f('ix_mfg_segment_mode'), table_name='mfg_segment')
    op.create_unique_constraint(op.f('uq_mfg_segments_tid_range'), 'mfg_segment', ['transcript_id', 'start_ts', 'end_ts'])
    op.drop_column('mfg_segment', 'mode')
    # ### end Alembic commands ###