"""MfgSegment_lang_update

Revision ID: 57bc65f74eec
Revises: 14a360988439
Create Date: 2025-09-06 16:47:39.578166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bc65f74eec'
down_revision = '14a360988439'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###