"""add mode to mfg_diarization + uq/index

Revision ID: 68be4f574763
Revises: ee003ecbc990
Create Date: 2025-10-06 12:05:47.293787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68be4f574763'
down_revision = 'ee003ecbc990'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfg_diarization', sa.Column('mode', sa.String(), server_default='diarize', nullable=False))
    op.drop_constraint(op.f('uq_mfg_diarization_chunk'), 'mfg_diarization', type_='unique')
    op.create_unique_constraint('uq_mfg_diarization_chunk', 'mfg_diarization', ['transcript_id', 'mode', 'start_ts', 'end_ts'])
    op.create_index('ix_mfg_diarization_tid_mode_start', 'mfg_diarization', ['transcript_id', 'mode', 'start_ts'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mfg_diarization_tid_mode_start', table_name='mfg_diarization')
    op.drop_constraint('uq_mfg_diarization_chunk', 'mfg_diarization', type_='unique')
    op.create_unique_constraint(op.f('uq_mfg_diarization_chunk'), 'mfg_diarization', ['transcript_id', 'start_ts', 'end_ts'])
    op.drop_column('mfg_diarization', 'mode')
    # ### end Alembic commands ###