"""MfgSegment_lang_update

Revision ID: 78a0f3432378
Revises: 57bc65f74eec
Create Date: 2025-09-06 16:49:45.588651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78a0f3432378'
down_revision = '57bc65f74eec'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfg_segment', sa.Column('lang', sa.String(), nullable=True))
    op.add_column('mfg_segment', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mfg_segment', 'updated_at')
    op.drop_column('mfg_segment', 'lang')
    # ### end Alembic commands ###