"""initial tables

Revision ID: 9f62774fdcaa
Revises: 70c3d238f43c
Create Date: 2025-08-27 19:35:20.505615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '9f62774fdcaa'
down_revision = '70c3d238f43c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfg_diarization',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('start_ts', sa.Float(), nullable=True),
    sa.Column('end_ts', sa.Float(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['mfg_transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mfg_chat')
    op.alter_column('mfg_embedding', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=768),
               existing_nullable=True)
    op.alter_column('mfg_segment', 'start_ts',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('mfg_segment', 'end_ts',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mfg_segment', 'end_ts',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('mfg_segment', 'start_ts',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('mfg_embedding', 'embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=True)
    op.create_table('mfg_chat',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('href_to', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secretaria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('voice_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['mfg_transcript.id'], name=op.f('mfg_chat_transcript_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mfg_chat_pkey'))
    )
    op.drop_table('mfg_diarization')
    # ### end Alembic commands ###