"""mfg_qa

Revision ID: b8a1afcaf2c1
Revises: 78a0f3432378
Create Date: 2025-09-09 13:57:01.839799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8a1afcaf2c1'
down_revision = '78a0f3432378'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfg_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfg_user_login'), 'mfg_user', ['login'], unique=True)
    op.create_table('mfg_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.BigInteger(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mfg_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfg_audit_log_object_id'), 'mfg_audit_log', ['object_id'], unique=False)
    op.create_index(op.f('ix_mfg_audit_log_user_id'), 'mfg_audit_log', ['user_id'], unique=False)
    op.create_table('mfg_qa',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['mfg_transcript.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['mfg_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfg_qa_transcript_id'), 'mfg_qa', ['transcript_id'], unique=False)
    op.create_index(op.f('ix_mfg_qa_user_id'), 'mfg_qa', ['user_id'], unique=False)
    op.add_column('mfg_transcript', sa.Column('title', sa.String(), nullable=True))
    op.add_column('mfg_transcript', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('mfg_transcript', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_mfg_transcript_user_id'), 'mfg_transcript', ['user_id'], unique=False)
    op.create_foreign_key(None, 'mfg_transcript', 'mfg_user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mfg_transcript', type_='foreignkey')
    op.drop_index(op.f('ix_mfg_transcript_user_id'), table_name='mfg_transcript')
    op.drop_column('mfg_transcript', 'user_id')
    op.drop_column('mfg_transcript', 'tags')
    op.drop_column('mfg_transcript', 'title')
    op.drop_index(op.f('ix_mfg_qa_user_id'), table_name='mfg_qa')
    op.drop_index(op.f('ix_mfg_qa_transcript_id'), table_name='mfg_qa')
    op.drop_table('mfg_qa')
    op.drop_index(op.f('ix_mfg_audit_log_user_id'), table_name='mfg_audit_log')
    op.drop_index(op.f('ix_mfg_audit_log_object_id'), table_name='mfg_audit_log')
    op.drop_table('mfg_audit_log')
    op.drop_index(op.f('ix_mfg_user_login'), table_name='mfg_user')
    op.drop_table('mfg_user')
    # ### end Alembic commands ###