"""file_id

Revision ID: ee003ecbc990
Revises: 1112c043cdaf
Create Date: 2025-09-22 17:09:02.197389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee003ecbc990'
down_revision = '1112c043cdaf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfg_file',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mfg_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mfg_file_user_created', 'mfg_file', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_mfg_file_user_id'), 'mfg_file', ['user_id'], unique=False)
    op.add_column('mfg_transcript', sa.Column('file_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'mfg_transcript', 'mfg_file', ['file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mfg_transcript', type_='foreignkey')
    op.drop_column('mfg_transcript', 'file_id')
    op.drop_index(op.f('ix_mfg_file_user_id'), table_name='mfg_file')
    op.drop_index('ix_mfg_file_user_created', table_name='mfg_file')
    op.drop_table('mfg_file')
    # ### end Alembic commands ###