"""add mode to MfgSummarySection + uq/index

Revision ID: fdea46fadbbe
Revises: 307ee2af9a09
Create Date: 2025-10-07 15:27:02.700488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdea46fadbbe'
down_revision = '307ee2af9a09'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfg_summary_section', sa.Column('mode', sa.String(), server_default='diarize', nullable=False))
    op.create_index(op.f('ix_mfg_summary_section_mode'), 'mfg_summary_section', ['mode'], unique=False)
    op.create_index('ix_mfg_summary_tid_mode', 'mfg_summary_section', ['transcript_id', 'mode'], unique=False)
    op.create_unique_constraint('uq_mfg_summary_section_tid_idx_mode', 'mfg_summary_section', ['transcript_id', 'idx', 'mode'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mfg_summary_section_tid_idx_mode', 'mfg_summary_section', type_='unique')
    op.drop_index('ix_mfg_summary_tid_mode', table_name='mfg_summary_section')
    op.drop_index(op.f('ix_mfg_summary_section_mode'), table_name='mfg_summary_section')
    op.drop_column('mfg_summary_section', 'mode')
    # ### end Alembic commands ###